report:
  config:
    id: 01
    name: Informe FECYT 2025
    authorization: role
    format: json
    operation: count
    
  data:
    - id: 01
      description: Publications
      operation: reviewers
      params: affiliation=URJC
      output:
        fields: userName

    - id: 02
      description: Publications
      operation: reviewers
      params: 
      output:
        fields: userName

