report:
  config:
    id: 01
    name: Informe FECYT 2025
    authorization: role
    format: json

  data:
    - id: 01
      description: Nombre de la Revista
      operation: userGroup
      params: 1
      output:
        fields: name

